name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4


    - name: Archive App
      run: |
        xcodebuild -scheme abledex \
          -xcconfig Configs/Secrets.xcconfig \
          -archivePath $PWD/build/abledex.xcarchive \
          -configuration Release \
          archive \
          CODE_SIGN_IDENTITY="-" \
          CODE_SIGNING_REQUIRED=NO

    - name: Export App
      run: |
        # Creates a simple export options plist
        cat <<EOF > ExportOptions.plist
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>mac-application</string>
            <key>destination</key>
            <string>export</string>
            <key>signingStyle</key>
            <string>manual</string>
        </dict>
        </plist>
        EOF

        xcodebuild -exportArchive \
          -archivePath $PWD/build/abledex.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $PWD/build \
          CODE_SIGN_IDENTITY="-" \
          CODE_SIGNING_REQUIRED=NO

    - name: Zip Application
      run: |
        cd build
        zip -r abledex.zip abledex.app

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/abledex.zip
        generate_release_notes: true
